M48
; DRILL file {KiCad 8.0.1} date 2024-08-08T22:12:17-0700
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-08-08T22:12:17-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1280
%
G90
G05
T1
X4.38Y-2.26
X4.38Y-3.66
X5.74Y-2.26
X5.74Y-3.66
T2
X4.8901Y-2.3663
X5.3901Y-2.3663
M30
